# Generated by Django 5.2.17 on 2026-09-29 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_schema_alignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['target_table', 'target_id'], name='activity_lo_entity__5a4970_idx'),
        ),
    ]
