# Generated by Django 5.2.17 on 2026-09-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_schema_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticitycertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authenticitycertificate',
            name='verification_code',
            field=models.CharField(db_column='verification_code', max_length=100, unique=True),
        ),
    ]
