# Generated by Django 6.1 on 2026-10-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_migrate_legacy_wishlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='was_out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
