# Generated by Django 5.2.17 on 2026-10-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notificatio_buyer_i_98c331_idx'),
        ('products', '0004_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.product'),
        ),
    ]
