# Generated by Django 5.2.17 on 2026-09-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_schema_alignment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'product_type'], name='catalog_ite_is_acti_a1d9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['game', 'set'], name='catalog_ite_game_id_8e88f1_idx'),
        ),
    ]
